### PR TITLE
Laravel 7 support

### LINKED ISSUE #58: Laravel 7 will support multiple mail drivers
See https://github.com/laravel/framework/pull/31073

If you stick with `MAIL_DRIVER=postmark` it does not seem to be a problem.

Using `Mail::mailer('postmark')->to(...)` might cause a problem:
https://github.com/craigpaul/laravel-postmark/blob/d2d72000e5ac908664c00478739ebb267484f8f9/src/PostmarkServiceProvider.php#L23-L25

### PR DESCRIPTION
**Pull request by mvdnbrk**
Resolves #58

### CODE REVIEW

**Comment by mvdnbrk** [comment]
@craigpaul Can you take a look? BC compatible with Laravel 6 😄

**Comment by craigpaul** [comment]
This is fantastic Mark! Nice work! We won't need a new major version then hey?

**Comment by mvdnbrk** [comment]
2.8 will do 👍

**Comment by craigpaul** [comment]
Just merged that scrutinizer PR, once these conflicts are good, I'll merge this 👍

**Comment by mvdnbrk** [comment]
Fixed!

**Pull request merged**
