### PR TITLE
WIP: Basic templates API support

### PR DESCRIPTION
**Pull request by MatanYadaev**
https://github.com/craigpaul/laravel-postmark/issues/28

### CODE REVIEW

**Comment by craigpaul** [comment]
Hey @MatanYadaev can you merge master back into your PR. I realized travis-ci wasn't running any checks and had to work with their support to get it back up and running. Thanks!

**Comment by MatanYadaev** [comment]
@craigpaul Please let me know if the implementation looks fine, there is anything I should fix or implement differently?

**Comment by craigpaul** [comment]
@MatanYadaev The implementation looks fine to me, but I have two main things I want to point out. 

1. The lack of tests for these new changes has dropped coverage below 100%, which I would like to maintain as a baseline for this library.

```
Summary:
  Classes: 33.33% (1/3)
  Methods: 70.00% (14/20)
  Lines:   67.18% (88/131)
```

2. I'd prefer not to use return types at this time. Instead, opting for doc blocks with up to date hints and descriptions.

Thanks! 😄

**Comment by craigpaul** [comment]
Thanks for the work @MatanYadaev but I have added and tagged this functionality now, so I'm going to close this PR. Appreciate the work! Let me know if you experience any issues with the template functionality! 😄

**Pull request closed without merging**
